# Generated by Django 5.0.9 on 2024-10-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_adjustment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_withheld",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_deduction",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SalaryDetailItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SalaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "detail_type",
                    models.TextField(
                        choices=[
                            ("PAY", "PAY"),
                            ("ADJ", "ADJUSTMENT"),
                            ("WIT", "WITHHELD"),
                            ("DED", "DEDUCTION"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="money.salary"
                    ),
                ),
                (
                    "salary_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.salarydetailitem",
                    ),
                ),
            ],
        ),
    ]
