# Generated by Django 5.0.9 on 2024-10-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_withheld', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_detail', models.JSONField()),
                ('adjustment_detail', models.JSONField()),
                ('tax_detail', models.JSONField()),
                ('deduction_detail', models.JSONField()),
            ],
        ),
    ]
