# Generated by Django 5.0.9 on 2024-10-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detail_type', models.TextField(choices=[('PAY', 'PAY'), ('ADJ', 'ADJUSTMENT'), ('WIT', 'WITHHELD'), ('DED', 'DEDUCTION')], max_length=3)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.salary')),
                ('salary_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.salarydetail')),
            ],
        ),
    ]
