# Generated by Django 5.0.9 on 2024-10-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_salarydetail_paydetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='adjustment_detail',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='deduction_detail',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='pay_detail',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='tax_detail',
        ),
    ]
