# Generated by Django 5.0.9 on 2024-10-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_remove_salary_adjustment_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalaryDetail',
            new_name='SalaryDetailItem',
        ),
    ]
