# Generated by Django 5.0.9 on 2024-10-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_rename_salarydetail_salarydetailitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayDetail',
            new_name='SalaryDetail',
        ),
    ]
